### ISSUE TITLE
Adding basic auth

### ISSUE THREAD

**Issue by og2t** [zeke/harp-buildpack#11]
Would it be possible to add a basic web based auth to the buildpack?
Thanks!

**Comment by zeke** [comment]
You can do this pretty easily with Harp itself: http://harpjs.com/docs/development/basicauth

Does that work for you?

**Comment by og2t** [comment]
Yeah, but since I compile the harp project, basic auth is not supported anymore. Would be nice if buildpack had also supported the _harp.json with auth details. Thansk!

**Comment by zeke** [comment]
Is it necessary to compile?

**Comment by og2t** [comment]
Not if Heroku can run harp server :) I didn't realise that was the case, thought Heroku compiled the project and run a static version of it.
