### ISSUE TITLE
Broken after new update.

### ISSUE THREAD

**Issue by upliftsleet1974** [zeke/harp-buildpack#15]
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

Have got this no matter what after new update...Its broken a few of my sites now.

**Comment by upliftsleet1974** [comment]
Still not working with any of my sites...

Also have tried some new ones.

**Comment by sintaxi** [comment]
Hi @upliftsleet1974, I work on harp. Please let me know if I can help out in any way.

**Comment by upliftsleet1974** [comment]
@sintaxi Sure....So I have tried following the Harp guide to install harp without the biuldpack and have made no progress Heroku rejects it no matter what I do....

**Comment by zeke** [comment]
Hey @upliftsleet1974 take a look at these comments: https://github.com/zeke/harp-buildpack/issues/12#issuecomment-75005388
